# Generated by Django 5.1.3 on 2024-11-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("planting_date", models.DateField(blank=True, null=True)),
                (
                    "harvest_duration",
                    models.IntegerField(
                        help_text="Estimated days to harvest", null=True
                    ),
                ),
                ("is_seasonal", models.BooleanField(default=False)),
            ],
        ),
    ]
